FROM openjdk:17.0.2-jdk

USER root

# INSTALLED PROJECT SPRING BOOT
RUN mkdir -p /apps/payment-api-listener

COPY docker-target/apps/ /apps/
COPY target/payment-api-listener.jar /apps/payment-api-listener/app/

RUN chmod +rx /apps/payment-api-listener/app/$application_name && chmod +rx /apps/docker-cmd.sh
RUN chown -R 3000:3000 /apps/

USER 3000
EXPOSE 8088


CMD /apps/docker-cmd.sh